/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Computer = ({ position, scale, setShowMessage }) => {
  const { nodes, materials } = useGLTF("/ComputerScreen.glb");

  const computerClickHandler = () => {
    console.log('computer clicked!');
    setShowMessage(true);
  }

  return (
    <group position={position} scale={scale} dispose={null} onClick={computerClickHandler} rotation-y={4.5}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computerScreen_2.geometry}
        material={materials.metalDark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computerScreen_2_1.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computerScreen_3.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computerScreen_3_1.geometry}
        material={materials.metalDark}
      />
    </group>
  );
}


useGLTF.preload("/ComputerScreen.glb");


export default Computer;