/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const DeskChair = (props) => {
  const { nodes, materials } = useGLTF("/DeskChair.glb");
  return (
    <group {...props} dispose={null} rotation-y={0}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Node-Mesh"].geometry}
        material={materials.Scoop_Chai}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.Scoop_Chai_1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Node-Mesh_2"].geometry}
        material={materials.Scoop_Chai_2}
      />
    </group>
  );
}

useGLTF.preload("/DeskChair.glb");

export default DeskChair;

